<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ProjectType>ProgramLibrary</ProjectType>
		<TargetFramework>net8</TargetFramework>
		<RootNamespace>PepperDash.Essentials.Plugins</RootNamespace>
		<AssemblyName>PepperDash.Essentials.Plugins.Crestron.Fusion</AssemblyName>
		<Configurations>Debug;Release</Configurations>
		<Deterministic>false</Deterministic>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<AssemblyTitle>EPI.Crestron.Fusion</AssemblyTitle>
		<Description>This software is a plugin designed to work as a part of PepperDash Essentials for Crestron control processors. This plugin allows for integration of Crestron Fusion.</Description>
		<PackageId>PepperDash.Essentials.Plugins.Crestron.Fusion</PackageId>
		<PackageProjectUrl>https://github.com/PepperDash/epi-crestron-fusion</PackageProjectUrl>
		<PackageTags>crestron 4series essentials plugin fusion</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Properties\**" />
		<EmbeddedResource Remove="Properties\**" />
		<None Remove="Properties\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Crestron.SimplSharp.SDK.ProgramLibrary" Version="2.21.128" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="PepperDashEssentials" Version="3.0.0-feat-routing-slot-online-sync.2">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
